### ISSUE TITLE
put_time is not member function of namespace std

### ISSUE THREAD

**Issue by isekaimaou1109** [ftraple/cpp-daemon-template#1]
This is the error, please help me fix it, i'm just a newbie in linux, thanks in advanced 
```
[ 33%] Building CXX object daemon/CMakeFiles/daemon-template.dir/source/daemon.cpp.o
In file included from /root/cpp-daemon-template/daemon/source/daemon.cpp:3:0:
/root/cpp-daemon-template/daemon/include/log.hpp: In function ‘std::string getLogTime(std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >)’:
/root/cpp-daemon-template/daemon/include/log.hpp:18:15: error: ‘put_time’ is not a member of ‘std’
     stream << std::put_time(gmtime(&epoch_seconds), "[%F_%T");
               ^
make[2]: *** [daemon/CMakeFiles/daemon-template.dir/source/daemon.cpp.o] Error 1
make[1]: *** [daemon/CMakeFiles/daemon-template.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by ftraple** [comment]
Depending on the version of the compiler you are using, this problem may occur. 
Check [this reference](https://en.cppreference.com/w/cpp/io/manip/put_time) for more information. 
You compiler needs to be compatible with `c++11`

**Comment by isekaimaou1109** [comment]
> Depending on the version of the compiler you are using, this problem may occur.
> Check [this reference](https://en.cppreference.com/w/cpp/io/manip/put_time) for more information.
> You compiler needs to be compatible with `c++11`

![upload(43)](https://user-images.githubusercontent.com/49366277/110717523-d13c3f80-823b-11eb-8c0a-e0356f60977f.png)

This is my compiler version, and when i search in google which versions gcc compiler support c++11 then i have found this page 
https://www.rosettacommons.org/docs/latest/build_documentation/Cxx11Support#:~:text=To%20see%20if%20your%20compiler,wish%20to%20use%20with%20Rosetta.&text=Acceptable%20versions%3A,%2B%2B%3A%20Version%204.8%20or%20later and they said me gcc ver 4.8 or later are acceptable. Sorry for my knowledge, i'm really a newbie so thanks in advanced and thanks for your quick reply.

**Comment by ftraple** [comment]
Hi, I was able to reproduce the problem. Go to the  [reference](https://en.cppreference.com/w/cpp/io/manip/put_time) page, scroll down until the example, and run the example with different types off compilers.
You will find out which exact compiler version is compatible with the `std :: put_time` method.

To solve this problem you have two solution:

* Solution 1: Update your compiler to a new version. **(If possible, recommended)**
* Solution 2: Remove the call to `std::put_time` and use some old C/C++ style to grab the date and time, example: [ctime](https://cplusplus.com/reference/ctime/ctime/)

**PS: Some of the old compilers do not implement all the C++11 features, that why it happens.**

**Comment by isekaimaou1109** [comment]
@ftraple nice and thanks for quickly reply.
